apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    type: proxy
    author: renu
spec:
  replicas: 2
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: web-pod
      labels:
        type: proxy
    spec:
      containers:
        - name: myweb
          image: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "350m"
          ports:
            - containerPort: 80
